### PR TITLE
Enhance Cmake usability - Removing local copy of Eigen 

### PR DESCRIPTION
**Pull request by pmoulon**
- Remove included Eigen third-party files
- Update the build doc according the local Eigen removal
- Use CMake 3.1 in order to use the new CX11 compiler settings
- Fix some compilation warning
- Export an cmake file opengv-config.cmake in order to use find_package(opengv) in new cmake project.

Here an example of the cmake command line use to:
- use a local Eigen download
- a local directory for installation

```
cmake ../opengv 
  -DEIGEN_INCLUDE_DIR="/home/Foo/Documents/Dev/third_party/eigen/" 
  -DBUILD_TESTS=ON 
  -DCMAKE_INSTALL_PREFIX="/home/Foo/Documents/Dev/opengv_Build/install" 
  -DINSTALL_OPENGV=ON

make
make install #sudo not required since we use a local installation
```

Then in order to use opengv in your local cmake based project:

```
find_package(opengv QUIET/REQUIRED/...)
if (opengv_FOUND)
  add_executable(main_opengv_demo main.cpp)
  target_link_libraries(main_opengv_demo opengv)
endif (opengv_FOUND)
```

Then to compile this project with a local opengv install, just do:

```
cmake ../myproject
 -DCMAKE_BUILD_TYPE=RELEASE 
 -Dopengv_DIR:STRING=/home/Foo/Documents/Dev/opengv_Build/install/CMake/
```

### CODE REVIEW

**Comment by pmoulon** [comment]
+laurentkneip Any feedback about the PR?

**Comment by laurentkneip** [comment]
Hey Pierre. Sorry for being late as usual. I checked this, it seems to be fine, however, could you add the commit message to the documentation? I would also rebuild and upload it so the information how to build the project is cristal clear. Believe it or not, but even without the hurdle of downloading and referring Eigen, there are already numerous requests from people having trouble with installing the library :)

**Comment by pmoulon** [comment]
Hi @laurentkneip No worries about the late answer. One day is better than never ;-)
What do you mean by "adding the commit message to the documentation"?
 - Does it means you want from me to update the *01_installation.dox* file?

I totally understand your point towards the duality that exists between self contained project and project with external third party.

I must also update this PR to remove the DINSTALL_OPENGV option since cmake can already deal with this as a native functionality (if you use ```make install```).

**Comment by pmoulon** [comment]
Hi @laurentkneip 
Documentation update (plus a minor fix about some unused code)

- Here command line used for classic usage (system installation + eigen library installed in system folders)
```
cmake ../opengv -DBUILD_TESTS=ON 
make
make test
sudo make install 
```

- Here an example of the cmake command line used to compile the project with a local Eigen and a local installation (this have been updated in the documentation).

```
cmake ../opengv 
  -DEIGEN_INCLUDE_DIR="/home/Foo/Documents/Dev/third_party/eigen/" 
  -DBUILD_TESTS=ON 
  -DCMAKE_INSTALL_PREFIX="/home/Foo/Documents/Dev/opengv_Build/install" 

make
make install #sudo not required since we use a local installation
```

Then in order to use opengv in your local cmake based project:
```
find_package(opengv QUIET/REQUIRED/...)
if (opengv_FOUND)
  add_executable(main_opengv_demo main.cpp)
  target_link_libraries(main_opengv_demo opengv)
endif (opengv_FOUND)
```

Then to compile this project with a local opengv install, just do:
```
cmake ../myproject
 -DCMAKE_BUILD_TYPE=RELEASE 
  #(optional) required only for local install
 -Dopengv_DIR:STRING=/home/Foo/Documents/Dev/opengv_Build/install/CMake/
```

**Comment by pmoulon** [comment]
👍  Thanks

**Comment by NikolausDemmel** [comment]
@pmoulon, do you happen to know what would be required here to make `find_package` also work on the build directory for opengv, i.e. not requiring the install step. For example both ceres and Pangolin allow this.

**Comment by NikolausDemmel** [comment]
This has been resolved, see https://github.com/laurentkneip/opengv/pull/45#issuecomment-430534282 . Sorry for double posting the same question.

**Pull request merged**
