### PR TITLE
Boostless opengv

### PR DESCRIPTION
**Pull request by pmoulon**
opengv core:
- remove boost by using C++11 features.

cmake:
- add detection of a compliant C++11 compiler,
- make tests compilation optional and use cmake testing functionality,
- allow out of source build.

### CODE REVIEW

**Comment by pmoulon** [comment]
@laurentkneip Any feedback on this putative PR?

**Comment by pmoulon** [comment]
Happy to see you back on github @laurentkneip :+1:

**Comment by laurentkneip** [comment]
It took a while didn't it? Many thanks for your modifications, it's great!!

**Comment by pmoulon** [comment]
You know what, one day is better than never ;-)

**Pull request merged**
