### PR TITLE
Add Python3 support

### PR DESCRIPTION
**Pull request by paulinus**
This PR adds support to build `pyopengv` for Python 3. The cmake option `BUILD_FOR_PYTHON3` has been added to enable it.

So running
```
cmake .. -DBUILD_PYTHON=ON -DBUILD_FOR_PYTHON3=ON
```
will configure the build to build `pyopengv` for Python 3

### CODE REVIEW

**Comment by ubuntuslave** [comment]
I would suggest changing line 3 in the `python/CMakeLists.txt` to have:

```
set(BOOST_PYTHON3_COMPONENT "python3" CACHE STRING "name of the Boost Python 3 component (python3, python-py36 or python-py37)")
```

Otherwise, the option behaves only as a *binary* ON/OFF variable.

**Comment by nflsalex** [comment]
Hey, Thanks for making python3 support happen. 

Seems like in this PR, we still only install to python2.7 packages?

**Comment by paulinus** [comment]
Done, @ubuntuslave. Thanks for pointing out.

@nflsalex, yes, the default install dir is still set for python 2.7 but you can change the installation destination by setting the `PYTHON_INSTALL_DIR` variable. I've used something like this for testing in ubuntu 17.10
```
    cmake .. -DBUILD_TESTS=OFF \
             -DBUILD_PYTHON=ON \
             -DBUILD_FOR_PYTHON3=ON \
             -DBOOST_PYTHON3_COMPONENT=python-py36 \
             -DPYTHON_INSTALL_DIR=/usr/local/lib/python3.6/dist-packages/
```

**Comment by ubuntuslave** [comment]
@nflsalex Also, when you toggle the advance settings (assuming you're using `ccmake`), you can also modify the Python include/library/directory paths. For example, in my case:

```
PYTHON_INCLUDE_DIR      /usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/include/py
PYTHON_INSTALL_DIR      /usr/local/lib/python3.6/site-packages
PYTHON_LIBRARY    /usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/libpyt    
```

**Comment by ubuntuslave** [comment]
@paulinus I'm trying to expose other OpenGV functions to Python, like for the noncentral case. Does anyone know if this work has happened already?

**Comment by paulinus** [comment]
@ubuntuslave, I don't know of anyone that tried exposing the noncentral case. It would be a great addition.

**Comment by ubuntuslave** [comment]
I just made a new pull request on top of this one with some added Python bindings for the non-central camera case. Not fully tested, but it works and looks fine. The pull request is 081dd6a926d2c1bf0bf9436226300c33defc5180

**Comment by laurentkneip** [comment]
This PR has conflicts now. Let us work on resolving them one-by-one

**Comment by paulinus** [comment]
closing this in favor of a future PR replacing boost-python with pybind11

**Pull request closed without merging**
