### PR TITLE
Changes for Python 3

### PR DESCRIPTION
**Pull request by nlw0**
These changes make the bindings work with Python 3.5. Not sure how to make it optional in CMake and support both...  Also some PEP8 changes.

### CODE REVIEW

**Comment by paulinus** [comment]
That is great @nlw0 !
Do you think is possible to make it work for both python 2 and 3?
maybe adding a cmake option?

**Comment by ubuntuslave** [comment]
Are you testing this on Linux or Mac OS X? I'm asking because in particularly, I was able to compile with Boost 1.64 and its python bindings with Python 3.6. However, when running the `test.py` script, I get this kind of error:

```
$ python3 tests.py
Traceback (most recent call last):
  File "tests.py", line 5, in <module>
    import pyopengv
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/pyopengv.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /usr/local/opt/boost-python/lib/libboost_python-mt.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python/lib/libboost_python-mt.dylib
```

**Comment by nlw0** [comment]
I tested only on my on Linux box, not sure how to make things more generic...

**Comment by paulinus** [comment]
Booth python 3 support and recent boost versions are handled by this newer PR https://github.com/laurentkneip/opengv/pull/62

**Pull request merged**
